### ISSUE TITLE
Sample Operation

### ISSUE THREAD

**Issue by zoetrope** [zoetrope/gh-mop#1]
## This issue is a sample to define a manual operation

```
# This is a comment
$ kubectl get pod

# You can omit `$`
kubectl get deployment

# This is a multiline command
$ kubectl get svc -n default \
    -o yaml \
    --show-managed-fields
```

ref: #5

**Comment by zoetrope** [comment]
```
Script started on 2023-03-25 21:36:47+09:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ 
[gh-mop#1:Step0]$ upload
Error: HTTP 400: Problems parsing JSON (https://api.github.com/repos/zoetrope/gh-mop/issues/1/comments)
Usage:
  mop upload [flags]

Flags:
  -h, --help   help for upload

Global Flags:
  -c, --config string   config file (default is $HOME/.mop.json)

exit status 1
[gh-mop#1:Step0]$ upload
Error: HTTP 400: Problems parsing JSON (https://api.github.com/repos/zoetrope/gh-mop/issues/1/comments)
Usage:
  mop upload [flags]

Flags:
  -h, --help   help for upload

Global Flags:
  -c, --config string   config file (default is $HOME/.mop.json)

exit status 1
[gh-mop#1:Step0]$ upload

```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-01 17:25:16+09:00 [TERM="xterm-256color" TTY="/dev/pts/3" COLUMNS="252" LINES="61"]
[gh-mop#1:Step0]$ 
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ 
[gh-mop#1:Step1]$ kubectl get deployment
No resources found in default namespace.
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ 
[gh-mop#1:Step2]$ kubectl get svc -n default \

    -o yaml \

    --show-managed-fields
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2023-04-01T03:50:18Z"
    labels:
      component: apiserver
      provider: kubernetes
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:component: {}
            f:provider: {}
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kube-apiserver
      operation: Update
      time: "2023-04-01T03:50:18Z"
    name: kubernetes
    namespace: default
    resourceVersion: "201"
    uid: 935692c7-2099-47c8-814c-345591071333
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
[gh-mop#1:Step2]$ upload

```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-01 23:13:51+09:00 [TERM="xterm-256color" TTY="/dev/pts/7" COLUMNS="252" LINES="61"]
[gh-mop#1:Step0]$ 
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ upload

```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-01 23:13:51+09:00 [TERM="xterm-256color" TTY="/dev/pts/7" COLUMNS="252" LINES="61"]
[gh-mop#1:Step0]$ 
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ upload
https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1492982887
229
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ nextuploadkubectl get poduploadnext
[gh-mop#1:Step1]$ kubectl get deployment-n sakube-system 
error: the server doesn't have a resource type "dep"
[gh-mop#1:Step1]$ kubectl -n kube-system get deployment
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
coredns   2/2     2            2           10h
[gh-mop#1:Step1]$ upload

```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-01 23:13:51+09:00 [TERM="xterm-256color" TTY="/dev/pts/7" COLUMNS="252" LINES="61"]
[gh-mop#1:Step0]$ 
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ upload
https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1492982887
229
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ nextuploadkubectl get poduploadnext
[gh-mop#1:Step1]$ kubectl get deployment-n sakube-system 
error: the server doesn't have a resource type "dep"
[gh-mop#1:Step1]$ kubectl -n kube-system get deployment
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
coredns   2/2     2            2           10h
[gh-mop#1:Step1]$ upload
https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1492983026
664
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ 
[gh-mop#1:Step2]$ kubectl get svc -n default \

    -o yaml \

    --show-managed-fields^C
[gh-mop#1:Step2]$ kubewatch kubectl get pod -w
(B
>[gh-mop#1:Step2]$ watch kubectl get pod -w
(BEvery 2.0s: kubectl get podnatte: Sat Apr  1 23:14:53 2023No resources found in default namespace.5
>[gh-mop#1:Step2]$ upload

```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-01 23:13:51+09:00 [TERM="xterm-256color" TTY="/dev/pts/7" COLUMNS="252" LINES="61"]
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ upload
https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1492982887
229
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ kubectl -n kube-system get dep
error: the server doesn't have a resource type "dep"
[gh-mop#1:Step1]$ kubectl -n kube-system get deployment
NAME      READY   UP-TO-DATE   AVAILABLE   AGE
coredns   2/2     2            2           10h
[gh-mop#1:Step1]$ upload
https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1492983026
664
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ kubectl get svc -n default \
    -o yaml \
    --show-managed-fields^C
[gh-mop#1:Step2]$ watch kubectl get pod -w
[gh-mop#1:Step2]$ watch kubectl get pod
[gh-mop#1:Step2]$ upload
https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1492983112
1095
[gh-mop#1:Step2]$ Script started on 2023-04-07 00:41:18+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ Script started on 2023-04-07 00:44:00+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ z











[gh-mop#1:Step0]$ Script started on 2023-04-07 00:44:54+09:00 [TERM="xterm-256color" TTY="/dev/pts/8" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ zScript started on 2023-04-07 00:45:31+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ kubectl get pod^C
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ kubectl get deployment^C
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ kubectl get svc -n default \
    -o yaml \
    --show-managed-fields^C
[gh-mop#1:Step2]$ next
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
github.com/zoetrope/gh-mop/cmd.glob..func1(0x2081180?, {0xc00046ede0, 0x2, 0x3?})
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/cmd/command.go:38 +0x1c6
github.com/spf13/cobra.(*Command).execute(0x2081180, {0xc00046ed50, 0x3, 0x3})
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x2081740)
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/vendor/github.com/spf13/cobra/command.go:968
github.com/zoetrope/gh-mop/cmd.Execute()
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/cmd/root.go:38 +0x25
main.main()
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/main.go:6 +0x17
exit status 2
[gh-mop#1:Step3]$ Script started on 2023-04-07 00:46:50+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ next
[gh-mop#1:Step3]$ kubectl api-resources
NAME   SHORTNAMES   APIVERSION   NAMESPACED   KIND
The connection to the server 127.0.0.1:34239 was refused - did you specify the right host or port?
[gh-mop#1:Step3]$ Script started on 2023-04-09 14:30:43+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="188" LINES="44"]
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ next
[gh-mop#1:Step3]$ next
[gh-mop#1:Step4]$ next
[gh-mop#1:Step5]$ exit

Script done on 2023-04-09 14:31:03+09:00 [COMMAND_EXIT_CODE="0"]
Script started on 2023-04-09 14:31:13+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ next
[gh-mop#1:Step3]$ next
[gh-mop#1:Step4]$ next
Error: The step number is out of range.
[gh-mop#1:Step4]$ next
Error: The step number is out of range.
panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
github.com/zoetrope/gh-mop/cmd.glob..func1(0x2083180?, {0xc0000a2cc0, 0x2, 0x3?})
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/cmd/command.go:38 +0x1c6
github.com/spf13/cobra.(*Command).execute(0x2083180, {0xc0000a2c60, 0x3, 0x3})
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/vendor/github.com/spf13/cobra/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x2083740)
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/vendor/github.com/spf13/cobra/command.go:968
github.com/zoetrope/gh-mop/cmd.Execute()
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/cmd/root.go:38 +0x25
main.main()
	/home/zoetro/go/src/github.com/zoetrope/gh-mop/main.go:6 +0x17
exit status 2
[gh-mop#1:Step4]$ Script started on 2023-04-09 14:33:55+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ next
[gh-mop#1:Step3]$ next
The last step is reached.
[gh-mop#1:Step3]$ next
The last step is reached.
[gh-mop#1:Step3]$ kubectl api-resources^C
[gh-mop#1:Step3]$ Script started on 2023-04-09 15:32:33+09:00 [TERM="xterm-256color" TTY="/dev/pts/4" COLUMNS="120" LINES="30"]
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ kubectl get pod^C
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ kubectl get deployment
No resources found in default namespace.
[gh-mop#1:Step1]$ upload
```

**Comment by zoetrope** [comment]
```
The result is uploaded to https://github.com/zoetrope/gh-mop/issues/1#issuecomment-1501053950
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ kubectl get svc -n default \
    -o yaml \
    --show-managed-fields
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2023-04-01T03:50:18Z"
    labels:
      component: apiserver
      provider: kubernetes
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:component: {}
            f:provider: {}
        f:spec:
          f:clusterIP: {}
          f:internalTrafficPolicy: {}
          f:ipFamilyPolicy: {}
          f:ports:
            .: {}
            k:{"port":443,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kube-apiserver
      operation: Update
      time: "2023-04-01T03:50:18Z"
    name: kubernetes
    namespace: default
    resourceVersion: "201"
    uid: 935692c7-2099-47c8-814c-345591071333
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
[gh-mop#1:Step2]$ next
[gh-mop#1:Step3]$ kubectl api-resources
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
bindings                                       v1                                     true         Binding
componentstatuses                 cs           v1                                     false        ComponentStatus
configmaps                        cm           v1                                     true         ConfigMap
endpoints                         ep           v1                                     true         Endpoints
events                            ev           v1                                     true         Event
limitranges                       limits       v1                                     true         LimitRange
namespaces                        ns           v1                                     false        Namespace
nodes                             no           v1                                     false        Node
persistentvolumeclaims            pvc          v1                                     true         PersistentVolumeClaim
persistentvolumes                 pv           v1                                     false        PersistentVolume
pods                              po           v1                                     true         Pod
podtemplates                                   v1                                     true         PodTemplate
replicationcontrollers            rc           v1                                     true         ReplicationController
resourcequotas                    quota        v1                                     true         ResourceQuota
secrets                                        v1                                     true         Secret
serviceaccounts                   sa           v1                                     true         ServiceAccount
services                          svc          v1                                     true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io/v1        false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io/v1        false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io/v1                false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io/v1              false        APIService
controllerrevisions                            apps/v1                                true         ControllerRevision
daemonsets                        ds           apps/v1                                true         DaemonSet
deployments                       deploy       apps/v1                                true         Deployment
replicasets                       rs           apps/v1                                true         ReplicaSet
statefulsets                      sts          apps/v1                                true         StatefulSet
tokenreviews                                   authentication.k8s.io/v1               false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io/v1                true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io/v1                false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io/v1                false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io/v1                false        SubjectAccessReview
horizontalpodautoscalers          hpa          autoscaling/v2                         true         HorizontalPodAutoscaler
cronjobs                          cj           batch/v1                               true         CronJob
jobs                                           batch/v1                               true         Job
certificatesigningrequests        csr          certificates.k8s.io/v1                 false        CertificateSigningRequest
leases                                         coordination.k8s.io/v1                 true         Lease
endpointslices                                 discovery.k8s.io/v1                    true         EndpointSlice
events                            ev           events.k8s.io/v1                       true         Event
flowschemas                                    flowcontrol.apiserver.k8s.io/v1beta3   false        FlowSchema
prioritylevelconfigurations                    flowcontrol.apiserver.k8s.io/v1beta3   false        PriorityLevelConfiguration
ingressclasses                                 networking.k8s.io/v1                   false        IngressClass
ingresses                         ing          networking.k8s.io/v1                   true         Ingress
networkpolicies                   netpol       networking.k8s.io/v1                   true         NetworkPolicy
runtimeclasses                                 node.k8s.io/v1                         false        RuntimeClass
poddisruptionbudgets              pdb          policy/v1                              true         PodDisruptionBudget
clusterrolebindings                            rbac.authorization.k8s.io/v1           false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io/v1           false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io/v1           true         RoleBinding
roles                                          rbac.authorization.k8s.io/v1           true         Role
priorityclasses                   pc           scheduling.k8s.io/v1                   false        PriorityClass
csidrivers                                     storage.k8s.io/v1                      false        CSIDriver
csinodes                                       storage.k8s.io/v1                      false        CSINode
csistoragecapacities                           storage.k8s.io/v1                      true         CSIStorageCapacity
storageclasses                    sc           storage.k8s.io/v1                      false        StorageClass
volumeattachments                              storage.k8s.io/v1                      false        VolumeAttachment
[gh-mop#1:Step3]$ next
The last step is reached.
[gh-mop#1:Step3]$ upload
```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-14 23:56:05+09:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="117" LINES="29"]
The operation is started. Issue: 1.
If you want to read the help, type "help".
[gh-mop#1:Step0]$ # Get the first command
[gh-mop#1:Step0]$ kubectl get pod
No resources found in default namespace.
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ # Get the second command
[gh-mop#1:Step1]$ kubectl get deployment
No resources found in default namespace.
[gh-mop#1:Step1]$ # Upload the result
[gh-mop#1:Step1]$ upload
```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-15 16:28:08+09:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="117" LINES="29"]
The operation is started. Issue: 1.
If you want to read the help, type "help".
[gh-mop#1:Step0]$ # Press 'Ctrl + t' to auto-complete the first command.
[gh-mop#1:Step0]$ kubectl get pod
NAME                      READY   STATUS    RESTARTS   AGE
sample-7fcb5b8bf6-fmpbv   1/1     Running   0          50s
sample-7fcb5b8bf6-qsf64   1/1     Running   0          49s
[gh-mop#1:Step0]$ # Run the 'next' command to proceed to the following command in the sequence.
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ # Press Ctrl + t again to auto-complete the second command.
[gh-mop#1:Step1]$ kubectl get deployment
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
sample   2/2     2            2           2m49s
[gh-mop#1:Step1]$ # Run 'upload' command to post the execution results in the comments of the GitHub Issue.
[gh-mop#1:Step1]$ upload
```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-15 16:44:44+09:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="117" LINES="29"]
The operation is started. Issue: 1.
If you want to read the help, type "help".
[gh-mop#1:Step0]$ # Press 'Ctrl + t' to auto-complete the first command.
[gh-mop#1:Step0]$ kubectl get pod
NAME                      READY   STATUS    RESTARTS   AGE
sample-7fcb5b8bf6-fmpbv   1/1     Running   0          17m
sample-7fcb5b8bf6-qsf64   1/1     Running   0          17m
[gh-mop#1:Step0]$ # Run the 'next' command to proceed to the following command in the sequence.
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ # Press 'Ctrl + t' again to auto-complete the second command.
[gh-mop#1:Step1]$ kubectl get deployment
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
sample   2/2     2            2           19m
[gh-mop#1:Step1]$ # Run 'upload' command to post the execution results in the comments of the GitHub Issue.
[gh-mop#1:Step1]$ upload
```

**Comment by zoetrope** [comment]
```
Script started on 2023-04-20 05:48:25+00:00 [TERM="xterm" TTY="/dev/pts/4" COLUMNS="194" LINES="48"]
The operation is started. Issue: 1.
If you want to read the help, type "help".
[gh-mop#1:Step0]$ help
commands:
  next: Move to the next step.
  prev: Move to the previous step.
  upload: Upload the results of executed commands.
shortcuts:
  C-t: Insert the next command into the current line.
  C-j: List the commands in the current operation.
  C-o: Search for a command from the utilities issue.
environment variables:
  MOP_REPO: The repository name.
  MOP_ISSUE: The issue number for the operation.
  MOP_STEP: The step number in the operation.
  MOP_OFFSET: The offset of the result in the issue comment.
  MOP_COMMAND_COUNT: The number of commands in the operation.
[gh-mop#1:Step0]$ kubectl get pod^C
[gh-mop#1:Step0]$ upload
```

**Comment by cybozu-neco** [comment]
```
Script started on 2023-04-20 05:55:22+00:00 [TERM="xterm" TTY="/dev/pts/1" COLUMNS="194" LINES="48"]
The operation is started. Issue: 1.
If you want to read the help, type "help".
[gh-mop#1:Step0]$ kubectl get pod^C
[gh-mop#1:Step0]$ upload
```

**Comment by cybozu-neco** [comment]
```
Script started on 2023-04-26 05:54:09+00:00 [TERM="xterm" TTY="/dev/pts/0" COLUMNS="324" LINES="76"]
The operation is started. Issue: 1.
If you want to read the help, type "help".
[gh-mop#1:Step0]$ help
commands:
  next: Move to the next step.
  prev: Move to the previous step.
  upload: Upload the results of executed commands.
shortcuts:
  C-t: Insert the next command into the current line.
  C-j: List the commands in the current operation.
  C-o: Search for a command from the utilities issue.
environment variables:
  MOP_REPO: The repository name.
  MOP_ISSUE: The issue number for the operation.
  MOP_STEP: The step number in the operation.
  MOP_OFFSET: The offset of the result in the issue comment.
  MOP_COMMAND_COUNT: The number of commands in the operation.
[gh-mop#1:Step0]$ help
commands:
  next: Move to the next step.
  prev: Move to the previous step.
  upload: Upload the results of executed commands.
shortcuts:
  C-t: Insert the next command into the current line.
  C-j: List the commands in the current operation.
  C-o: Search for a command from the utilities issue.
environment variables:
  MOP_REPO: The repository name.
  MOP_ISSUE: The issue number for the operation.
  MOP_STEP: The step number in the operation.
  MOP_OFFSET: The offset of the result in the issue comment.
  MOP_COMMAND_COUNT: The number of commands in the operation.
[gh-mop#1:Step0]$ kubectl get pod^C
[gh-mop#1:Step0]$ next
[gh-mop#1:Step1]$ kubectl get deployment^C
[gh-mop#1:Step1]$ next
[gh-mop#1:Step2]$ kubectl get svc -n default \
    -o yaml \
    --show-managed-fields
error: You must be logged in to the server (Unauthorized)
[gh-mop#1:Step2]$ upload
```
